### ISSUE TITLE
Create a tutorial type set up for user

### ISSUE THREAD

**Issue by besteman** [what-to-do/team-project#69]
To create a helper for the user

- [x] Make a button in the nav bar called Help
- [x] Create an event listener for it
- [x] Make a function that will help the user

Design freedom.

**Comment by rdotchin** [comment]
Jessica, I will be working on the flickr api tomorrow.  If you finish your tasks and want to take this on send me a slack message.

**Comment by rdotchin** [comment]
used https://github.com/usablica/intro.js/
